# Generated by Django 2.2.5 on 2022-06-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220612_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomtype',
            new_name='room_type',
        ),
    ]
